version: '3.0'
volumes:
  mysql-data:
services:
  mysql-standalone:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=ThriftyFriend
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  springboot:
    image: springboot-docker-container
    ports:
      - "80:8080"
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone/ThriftyFriend?serverTimezone=America/Los_Angeles
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    build:
      context: './'
      dockerfile: Dockerfile
    depends_on:
      - mysql-standalone

